language: python
python:
 - 3.6
script:
 - python3 blackjack_unittest.py
 - python3 blackjack_integrationtest.py
deploy:
 provider: releases
 skip_cleanup: true
 github_token: $github_token
 on:
  repo: chriseichstedt/CS491Eichstedt
  tags: true

	
