language: python
python:
 - 3.6
script:
 - python3 blackjack_unittest.py
 - python3 blackjack_integrationtest.py
deploy:
 provider: pages
 skip_cleanup: true
 github_token: 6bc979868146140e28097191b12695504337fdeb
 local_dir: build
 on:
  branch: master

	
