language: python
python:
	- 3.6
script:
	- python3 blackjack_unittest.py 
	- python3 blackjack_integrationtest.py
deploy:
	provider: releases
	api_key: "GITHUB OAUTH TOKEN"
        file:
		-blackjack.py
		-card.py
		-deck.py
		-hand.py
	skip_cleanup: true
	on:
		tags: true

	
