language: python
python:
 - 3.6
script:
 - python3 blackjack_unittest.py
 - python3 blackjack_integrationtest.py
deploy:
 provider: releases
 github_token: $github_token
 file: 'release.zip'
 skip_cleanup: true
 on:
  tags: true
