language: python
python:
 - 3.6
script:
 - python3 blackjack_unittest.py
 - python3 blackjack_integrationtest.py
deploy:
 provider: releases
 api_key: $TOKEN
 file: "blackjack"
 skip_cleanup: true
 on:
  tags: false 

	
